### ISSUE TITLE
-2 - -3

### ISSUE THREAD

**Issue by Tastypotato245** [Tastypotato245/OOP_Project02#4]
memory leak 
and 

output : 5

**Comment by novaprospectCAU** [comment]
문제가 발생하는 경우
1. 음수 + 양수
2. 양수 + 음수
3. 음수 - 음수
4. 양수 - 양수
-> 힙메모리 범위를 넘어선 참조로 인한 에러 발생(메모리 릭을 넘어서서 결과가 나오지 않는 중대한 버그임)

**Comment by cho0h5** [comment]
좋은 브리핑💥

**Comment by novaprospectCAU** [comment]
fix_heapOverflow 브랜치 체크좀 해줘. 문제 해결했어

**Comment by novaprospectCAU** [comment]
별건 아닌데 for문 범위가 하나 넘어가서 고쳤어

**Comment by novaprospectCAU** [comment]
여전히 터지네. 범위하나 고쳤는데 다른데서 터진다

**Comment by novaprospectCAU** [comment]
문제가 발생하는 부분 : 수정
1. 양수 + 음수(값이 다름)
2. 양수 - 양수(부호가 반대)
3. 양수 - 음수(부호가 반대)
4. 음수 - 양수(부호가 반대)
5. 음수 - 음수(값이 다름)

->큰 수에 대한 테스트도 필요함

**Comment by cho0h5** [comment]
> 문제가 발생하는 부분 : 수정
> 
>     1. 양수 + 음수(값이 다름)
> 
>     2. 양수 - 양수(부호가 반대)
> 
>     3. 양수 - 음수(부호가 반대)
> 
>     4. 음수 - 양수(부호가 반대)
> 
>     5. 음수 - 음수(값이 다름)
> 
> 
> ->큰 수에 대한 테스트도 필요함

3, 4 -> #e9e3a0c 해결

**Comment by novaprospectCAU** [comment]
오케이 테스트 해봤는데 다 통과했어, 메모리 릭도 없네, 수고했어!
